version = 5.6.0
archive_dir = /etc/letsencrypt/archive/teachergen.ru
cert = /etc/letsencrypt/live/teachergen.ru/cert.pem
privkey = /etc/letsencrypt/live/teachergen.ru/privkey.pem
chain = /etc/letsencrypt/live/teachergen.ru/chain.pem
fullchain = /etc/letsencrypt/live/teachergen.ru/fullchain.pem
[renewalparams]
account = 39eba860d558098d6177b7416cc2e1b7
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
teachergen.ru = /var/www/certbot
www.teachergen.ru = /var/www/certbot
